name: Deploy Docker App to AWS

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy and Cleanup Docker on AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@65.0.127.14 <<EOF
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker \$USER
            fi


            # Stop and remove the previous container of the app
            docker stop uno-container || true
            docker rm uno-container || true

            # Remove the previous image of the app
            docker rmi uno || true

            # Pull latest code
            cd /home/ubuntu/projectUNO
            git pull origin main

            # Build and run new Docker container
            docker build -t uno .
            docker run -d --name uno-container -p 8000:8000 uno
          EOF
